app:
  name: "Finsys Transaction Service"
  
server:
  host: localhost
  port: 8080

database:
  name: ''
  host: localhost
  port: 5432
  user: ''
  password: ''

redis:
  host: localhost
  port: 6379

sqs:
  transactionQueue: "finsys-transactions-queue.fifo"
  transactionDLQ: "finsys-transactions-deadletter-queue.fifo"
  notificationQueue: "finsys-notifications-queue.fifo"
  notificationDLQ: "finsys-notifications-deadletter-queue.fifo"
  maxNumberOfMessages: 10
  waitTimeSeconds: 20


aws:
  host: http://localhost:4566
  region: us-east-2